export const USER_ADD_PRODUCT_REQUEST = "USER_ADD_PRODUCT_REQUEST";
export const USER_ADD_PRODUCT_SUCCESS = "USER_ADD_PRODUCT_SUCCESS";
export const USER_ADD_PRODUCT_FAIL = "USER_ADD_PRODUCT_FAIL";

export const USER_DELETE_PRODUCT_REQUEST = "USER_DELETE_PRODUCT_REQUEST";
export const USER_DELETE_PRODUCT_SUCCESS = "USER_DELETE_PRODUCT_SUCCESS";
export const USER_DELETE_PRODUCT_FAIL = "USER_DELETE_PRODUCT_FAIL";

export const USER_EDIT_PRODUCT_REQUEST = "USER_EDIT_PRODUCT_REQUEST";
export const USER_EDIT_PRODUCT_SUCCESS = "USER_EDIT_PRODUCT_SUCCESS";
export const USER_EDIT_PRODUCT_FAIL = "USER_EDIT_PRODUCT_FAIL";

export const USER_ADD_DELIVERY_REQUEST = "USER_ADD_DELIVERY_REQUEST";
export const USER_ADD_DELIVERY_SUCCESS = "USER_ADD_DELIVERY_SUCCESS";
export const USER_ADD_DELIVERY_FAIL = "USER_ADD_DELIVERY_FAIL";

export const ADMIN_SALES_REPORT_REQUEST = "ADMIN_SALES_REPORT_REQUEST";
export const ADMIN_SALES_REPORT_SUCCESS = "ADMIN_SALES_REPORT_SUCCESS";
export const ADMIN_SALES_REPORT_FAIL = "ADMIN_SALES_REPORT_FAIL";

export const ADMIN_PENDING_DELIVERY_REQUEST = "ADMIN_PENDING_DELIVERY_REQUEST";
export const ADMIN_PENDING_DELIVERY_SUCCESS = "ADMIN_PENDING_DELIVERY_SUCCESS";
export const ADMIN_PENDING_DELIVERY_FAIL = "ADMIN_PENDING_DELIVERY_FAIL";

export const ADMIN_PAYMENT_STATUS_REQUEST = "ADMIN_PAYMENT_STATUS_REQUEST";
export const ADMIN_PAYMENT_STATUS_SUCCESS = "ADMIN_PAYMENT_STATUS_SUCCESS";
export const ADMIN_PAYMENT_STATUS_FAIL = "ADMIN_PAYMENT_STATUS_FAIL";
