export const CUSTOMER_ADD_TO_CART_REQUEST = "CUSTOMER_ADD_TO_CART_REQUEST";
export const CUSTOMER_ADD_TO_CART_SUCCESS = "CUSTOMER_ADD_TO_CART_SUCCESS";
export const CUSTOMER_ADD_TO_CART_FAIL = "CUSTOMER_ADD_TO_CART_FAIL";

export const CUSTOMER_GET_CART_REQUEST = "CUSTOMER_GET_CART_REQUEST";
export const CUSTOMER_GET_CART_SUCCESS = "CUSTOMER_GET_CART_SUCCESS";
export const CUSTOMER_GET_CART_FAIL = "CUSTOMER_GET_CART_FAIL";

export const CUSTOMER_REMOVE_CART_REQUEST = "CUSTOMER_REMOVE_CART_REQUEST";
export const CUSTOMER_REMOVE_CART_SUCCESS = "CUSTOMER_REMOVE_CART_SUCCESS";
export const CUSTOMER_REMOVE_CART_FAIL = "CUSTOMER_REMOVE_CART_FAIL";

export const CUSTOMER_CHECKOUT_REQUEST = "CUSTOMER_CHECKOUT_REQUEST";
export const CUSTOMER_CHECKOUT_SUCCESS = "CUSTOMER_CHECKOUT_SUCCESS";
export const CUSTOMER_CHECKOUT_FAIL = "CUSTOMER_CHECKOUT_FAIL";

export const CUSTOMER_PAYMENT_REQUEST = "CUSTOMER_PAYMENT_REQUEST";
export const CUSTOMER_PAYMENT_SUCCESS = "CUSTOMER_PAYMENT_SUCCESS";
export const CUSTOMER_PAYMENT_FAIL = "CUSTOMER_PAYMENT_FAIL";
