export const DELIVERY_PENDING_DELIVERY_REQUEST =
  "DELIVERY_PENDING_DELIVERY_REQUEST";
export const DELIVERY_PENDING_DELIVERY_SUCCESS =
  "DELIVERY_PENDING_DELIVERY_SUCCESS";
export const DELIVERY_PENDING_DELIVERY_FAIL = "DELIVERY_PENDING_DELIVERY_FAIL";

export const DELIVERY_STATUS_UPDATE_REQUEST = "DELIVERY_STATUS_UPDATE_REQUEST";
export const DELIVERY_STATUS_UPDATE_SUCCESS = "DELIVERY_STATUS_UPDATE_SUCCESS";
export const DELIVERY_STATUS_UPDATE_FAIL = "DELIVERY_STATUS_UPDATE_FAIL";

export const PAYMENT_PENDING_STATUS_REQUEST = "PAYMENT_PENDING_STATUS_REQUEST";
export const PAYMENT_PENDING_STATUS_SUCCESS = "PAYMENT_PENDING_STATUS_SUCCESS";
export const PAYMENT_PENDING_STATUS_FAIL = "PAYMENT_PENDING_STATUS_FAIL";

export const PAYMENT_STATUS_UPDATE_REQUEST = "PAYMENT_STATUS_UPDATE_REQUEST";
export const PAYMENT_STATUS_UPDATE_SUCCESS = "PAYMENT_STATUS_UPDATE_SUCCESS";
export const PAYMENT_STATUS_UPDATE_FAIL = "PAYMENT_STATUS_UPDATE_FAIL";

export const DELIVERY_VIEW_ORDERS_REQUEST = "DELIVERY_VIEW_ORDERS_REQUEST";
export const DELIVERY_VIEW_ORDERS_SUCCESS = "DELIVERY_VIEW_ORDERS_SUCCESS";
export const DELIVERY_VIEW_ORDERS_FAIL = "DELIVERY_VIEW_ORDERS_FAIL";
