export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_EDIT_PROFILE_REQUEST = "USER_EDIT_PROFILE_REQUEST";
export const USER_EDIT_PROFILE_SUCCESS = "USER_EDIT_PROFILE_SUCCESS";
export const USER_EDIT_PROFILE_FAIL = "USER_EDIT_PROFILE_FAIL";

export const USER_EDIT_PASSWORD_REQUEST = "USER_EDIT_PASSWORD_REQUEST";
export const USER_EDIT_PASSWORD_SUCCESS = "USER_EDIT_PASSWORD_SUCCESS";
export const USER_EDIT_PASSWORD_FAIL = "USER_EDIT_PASSWORD_FAIL";

export const USER_VIEW_PRODUCTS_REQUEST = "USER_VIEW_PRODUCTS_REQUEST";
export const USER_VIEW_PRODUCTS_SUCCESS = "USER_VIEW_PRODUCTS_SUCCESS";
export const USER_VIEW_PRODUCTS_FAIL = "USER_VIEW_PRODUCTS_FAIL";

export const USER_GET_ORDER_REQUEST = "USER_GET_ORDER_REQUEST";
export const USER_GET_ORDER_SUCCESS = "USER_GET_ORDER_SUCCESS";
export const USER_GET_ORDER_FAIL = "USER_GET_ORDER_FAIL";

export const USER_FORGOT_PASSWORD_REQUEST = "USER_FORGOT_PASSWORD_REQUEST";
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAIL = "USER_FORGOT_PASSWORD_FAIL";
